-- =====================================================================
-- product-service 首个 Flyway 迁移
-- schema: product_svc
-- 7 张业务表:category / product / product_sku / product_image /
--            product_faq / product_review / recommendation_log
-- 与 monolith Category/Product/... entity 字段对齐
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS product_svc;

SET search_path TO product_svc;

-- ---------- category(商品品类,扁平一级)----------
CREATE TABLE category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    description VARCHAR(500),
    icon_url    VARCHAR(500),
    sort_order  INTEGER DEFAULT 0,
    is_active   SMALLINT DEFAULT 1,               -- 1=启用, 0=禁用(与 monolith TINYINT(1) 对齐)
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_category_sort ON category(sort_order);

COMMENT ON TABLE category IS '商品分类(扁平一级,无 parent_id)';

-- ---------- product(商品主表)----------
CREATE TABLE product (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code     VARCHAR(50) NOT NULL,
    category_id      BIGINT NOT NULL,
    title            VARCHAR(500) NOT NULL,
    brand            VARCHAR(100),
    sub_category     VARCHAR(50),
    base_price       NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    image_url        VARCHAR(500),
    description      TEXT,
    tags             VARCHAR(1000),
    rating           NUMERIC(3, 2) DEFAULT 0.00,
    review_count     INTEGER DEFAULT 0,
    sales_count      INTEGER DEFAULT 0,
    status           SMALLINT DEFAULT 1,           -- 1=上架, 0=下架
    embedding_status SMALLINT DEFAULT 0,           -- 0=未处理, 1=已生成向量
    create_time      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_product_code ON product(product_code);
CREATE INDEX idx_product_category ON product(category_id);
CREATE INDEX idx_product_brand ON product(brand);
CREATE INDEX idx_product_sub_category ON product(sub_category);
CREATE INDEX idx_product_status ON product(status);
CREATE INDEX idx_product_embedding_status ON product(embedding_status);
CREATE INDEX idx_product_price ON product(base_price);
CREATE INDEX idx_product_rating ON product(rating DESC);
CREATE INDEX idx_product_sales ON product(sales_count DESC);

COMMENT ON TABLE product IS '商品主表';
COMMENT ON COLUMN product.status IS '1=上架, 0=下架';
COMMENT ON COLUMN product.embedding_status IS '0=未处理, 1=已生成向量';

-- ---------- product_sku(商品 SKU)----------
CREATE TABLE product_sku (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL,
    sku_code    VARCHAR(50) NOT NULL,
    properties  JSONB,                             -- {"容量":"30ml"} 等
    price       NUMERIC(10, 2) NOT NULL,
    stock       INTEGER DEFAULT 999,
    is_default  SMALLINT DEFAULT 0,                -- 1=默认规格, 0=非默认
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_sku_code ON product_sku(sku_code);
CREATE INDEX idx_sku_product ON product_sku(product_id);

COMMENT ON TABLE product_sku IS '商品规格(SKU)';
COMMENT ON COLUMN product_sku.properties IS 'JSON 规格键值,如 {"容量":"30ml","颜色":"红"}';

-- ---------- product_image(商品图片)----------
CREATE TABLE product_image (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL,
    image_url   VARCHAR(500) NOT NULL,
    image_type  VARCHAR(20) DEFAULT 'detail',     -- main/detail/scene
    sort_order  INTEGER DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_image_product ON product_image(product_id);

COMMENT ON COLUMN product_image.image_type IS 'main=主图, detail=详情图, scene=场景图';

-- ---------- product_faq(商品 FAQ)----------
CREATE TABLE product_faq (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL,
    question    VARCHAR(500) NOT NULL,
    answer      TEXT NOT NULL,
    sort_order  INTEGER DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_faq_product ON product_faq(product_id);

-- ---------- product_review(商品评价)----------
CREATE TABLE product_review (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   BIGINT NOT NULL,
    user_id      BIGINT,                          -- 可空:支持外部导入无用户绑定的评价
    nickname     VARCHAR(50) DEFAULT '匿名用户',
    rating       SMALLINT NOT NULL,               -- 1-5 星
    content      TEXT NOT NULL,
    is_anonymous SMALLINT DEFAULT 0,               -- 1=匿名, 0=非匿名
    create_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_review_product ON product_review(product_id);
CREATE INDEX idx_review_user ON product_review(user_id);
CREATE INDEX idx_review_rating ON product_review(rating);

COMMENT ON COLUMN product_review.rating IS '1-5 星';

-- ---------- recommendation_log(推荐日志)----------
CREATE TABLE recommendation_log (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT,               -- 可空,支持匿名推荐
    session_id              VARCHAR(64),
    message_id              BIGINT,               -- 关联 chat 的消息 id(跨服务字段,不加 FK)
    query                   TEXT,
    intent                  VARCHAR(50),
    recommended_product_ids JSONB,                -- List<Long>
    recommend_reason        TEXT,
    agent_reasoning         TEXT,
    user_clicked            SMALLINT DEFAULT 0,   -- 1=点击, 0=未点击
    user_feedback           SMALLINT,             -- 1=满意, 0=不满意
    create_time             TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rec_user ON recommendation_log(user_id);
CREATE INDEX idx_rec_session ON recommendation_log(session_id);
CREATE INDEX idx_rec_intent ON recommendation_log(intent);
CREATE INDEX idx_rec_create_time ON recommendation_log(create_time DESC);

COMMENT ON TABLE recommendation_log IS 'AI 商品推荐日志(供离线分析与推荐算法迭代)';
