-- =====================================================================
-- user-service 首个 Flyway 迁移
-- schema: user_svc
-- 4 张业务表:users / address / user_browse_history / user_favorite
-- 与 monolith User/Address/UserBrowseHistory/UserFavorite entity 字段对齐
-- =====================================================================

-- ---------- schema ----------
-- Flyway 配置里已设 schemas=user_svc,会自动创建,这里显式声明保证独立执行时也可用
CREATE SCHEMA IF NOT EXISTS user_svc;

SET search_path TO user_svc;

-- ---------- users ----------
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(255),
    phone           VARCHAR(20),
    password        VARCHAR(255),
    avatar_url      VARCHAR(500),
    gender          INTEGER,             -- 0=未知, 1=男, 2=女
    age_range       VARCHAR(20),         -- 如 "18-24"
    skin_type       VARCHAR(50),         -- 如 "干皮" / "油皮"
    preference_tags JSONB,               -- List<String>,MyBatis-Plus JacksonTypeHandler
    status          INTEGER DEFAULT 1,   -- 1=正常, 0=禁用
    create_time     TIMESTAMP,
    update_time     TIMESTAMP
);

COMMENT ON TABLE users IS '用户主表';
COMMENT ON COLUMN users.gender IS '0=未知, 1=男, 2=女';
COMMENT ON COLUMN users.status IS '1=正常, 0=禁用';

CREATE INDEX idx_users_phone ON users(phone);

-- ---------- address ----------
CREATE TABLE address (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    receiver_name VARCHAR(100),
    phone         VARCHAR(20),
    province      VARCHAR(50),
    city          VARCHAR(50),
    district      VARCHAR(50),
    detail        VARCHAR(500),
    is_default    INTEGER DEFAULT 0,     -- 1=默认地址
    create_time   TIMESTAMP,
    update_time   TIMESTAMP              -- 相较 monolith 新增,便于追踪
);

COMMENT ON TABLE address IS '收货地址簿';
COMMENT ON COLUMN address.is_default IS '1=默认地址, 0=非默认';

CREATE INDEX idx_address_user_id ON address(user_id);

-- ---------- user_browse_history ----------
CREATE TABLE user_browse_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    product_id   BIGINT NOT NULL,
    source       VARCHAR(100),           -- 推荐 / 搜索 / 详情页
    duration_sec INTEGER,                -- 停留时长(秒)
    create_time  TIMESTAMP
);

COMMENT ON TABLE user_browse_history IS '商品浏览历史(去重后保留最新一条)';

CREATE INDEX idx_ubh_user_id ON user_browse_history(user_id);
CREATE INDEX idx_ubh_user_product ON user_browse_history(user_id, product_id);

-- ---------- user_favorite ----------
CREATE TABLE user_favorite (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    product_id  BIGINT NOT NULL,
    create_time TIMESTAMP
);

COMMENT ON TABLE user_favorite IS '用户收藏';

CREATE INDEX idx_uf_user_id ON user_favorite(user_id);
CREATE UNIQUE INDEX idx_uf_user_product ON user_favorite(user_id, product_id);
