-- chat-service Flyway V1: chat_svc schema + 11 张表

CREATE SCHEMA IF NOT EXISTS chat_svc;
SET search_path TO chat_svc;

-- ---------- conversation ----------
CREATE TABLE conversation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    title       VARCHAR(255),
    scene       VARCHAR(64),       -- admin_chat / normal
    is_pinned   SMALLINT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_conv_user ON conversation(user_id);

-- ---------- message (3 个 JSONB 字段, autoResultMap=true) ----------
CREATE TABLE message (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id  BIGINT,
    role             VARCHAR(32),       -- user / assistant
    content          TEXT,
    message_type     VARCHAR(32),       -- text / product_card / cart_selection / confirm_card
    product_cards    JSONB,             -- List<Map> 推荐商品卡
    confirm_card     JSONB,             -- Map 确认卡
    cart_selection   JSONB,             -- Map 购物车选择卡
    image_url        VARCHAR(512),
    sources          TEXT,              -- AI 引用来源 JSON
    task_type        VARCHAR(64),       -- shopping / knowledge_qa
    importance_score DOUBLE PRECISION,
    feedback_type    VARCHAR(32),       -- like / dislike
    feedback_time    TIMESTAMP,
    create_time      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_msg_conv ON message(conversation_id);

-- ---------- notice ----------
CREATE TABLE notice (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255),
    content     TEXT,
    notice_type VARCHAR(64),       -- SYSTEM / ACTIVITY
    file_path   VARCHAR(512),
    is_active   SMALLINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------- agent_run (UUID 主键, MyBatis-Plus IdType.ASSIGN_UUID) ----------
CREATE TABLE agent_run (
    id              VARCHAR(64) PRIMARY KEY,
    run_id          VARCHAR(64),
    trace_id        VARCHAR(64),
    conversation_id VARCHAR(64),
    user_id         VARCHAR(64),
    status          VARCHAR(32),       -- running / completed / failed / cancelled
    goal            VARCHAR(512),
    intent          VARCHAR(255),
    start_time      TIMESTAMP,
    end_time        TIMESTAMP,
    input           TEXT,
    output          TEXT,
    error_message   TEXT,
    error_code      VARCHAR(64),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_arun_run ON agent_run(run_id);

-- ---------- agent_step ----------
CREATE TABLE agent_step (
    id            VARCHAR(64) PRIMARY KEY,
    run_id        VARCHAR(64),
    step_type     VARCHAR(64),
    step_name     VARCHAR(255),
    status        VARCHAR(32),
    input         TEXT,
    output        TEXT,
    error_message TEXT,
    start_time    TIMESTAMP,
    end_time      TIMESTAMP,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    duration_ms   BIGINT,
    tool_call_id  VARCHAR(64)
);
CREATE INDEX idx_astep_run ON agent_step(run_id);

-- ---------- tool_call ----------
CREATE TABLE tool_call (
    id            VARCHAR(64) PRIMARY KEY,
    tool_call_id  VARCHAR(64),
    run_id        VARCHAR(64),
    tool_name     VARCHAR(128),
    input_params  TEXT,                 -- JSON
    output        TEXT,
    status        VARCHAR(32),
    duration_ms   BIGINT,
    error_message TEXT,
    timestamp     TIMESTAMP,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------- qa_log ----------
CREATE TABLE qa_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    conversation_id BIGINT,
    question        TEXT,
    answer          TEXT,
    task_type       VARCHAR(64),
    duration_ms     BIGINT,
    feedback_type   VARCHAR(32),
    feedback_time   TIMESTAMP,
    create_time     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_qalog_user ON qa_log(user_id);

-- ---------- qa_unanswered ----------
CREATE TABLE qa_unanswered (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question     TEXT,
    count        INTEGER,
    last_user_id BIGINT,
    create_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------- conversation_context ----------
CREATE TABLE conversation_context (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id    BIGINT,
    user_id            BIGINT,
    summary            TEXT,                -- 对话摘要 JSON
    embedding          TEXT,                -- 向量 JSON
    user_preferences   TEXT,                -- 偏好 JSON
    mentioned_products TEXT,                -- 提及商品 JSON
    window_size        INTEGER DEFAULT 10,
    importance_score   DOUBLE PRECISION,
    update_time        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_time        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_cctx_conv ON conversation_context(conversation_id);

-- ---------- knowledge_doc ----------
CREATE TABLE knowledge_doc (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_name     VARCHAR(255),
    file_path    VARCHAR(512),
    category_id  BIGINT,
    doc_type     VARCHAR(64),
    status       VARCHAR(32),              -- PENDING / PROCESSING / COMPLETED / FAILED
    error_message TEXT,
    create_time  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------- knowledge_chunk ----------
CREATE TABLE knowledge_chunk (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id      BIGINT,
    product_id  BIGINT,                    -- 跨域引用 product_svc.product.id
    chunk_text  TEXT,
    chunk_index INTEGER,
    chunk_type  VARCHAR(32),               -- TEXT / TABLE / IMAGE_CAPTION
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_kchunk_doc ON knowledge_chunk(doc_id);
