-- =====================================================================
-- 001_user_svc.sql — user_svc schema 完整结构快照(开发期参考)
-- 来源:Navicat Premium 导出 PostgreSQL 16(2026-07-21)
-- 警告:不要直接跑! 含 DROP TABLE IF EXISTS,会清空现有数据。
-- 用途:了解数据库结构 / 对照 Flyway V1/V2 迁移 / 新人入门。
-- =====================================================================


-- ----------------------------
-- Sequence structure for address_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "user_svc"."address_id_seq";
CREATE SEQUENCE "user_svc"."address_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for user_browse_history_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "user_svc"."user_browse_history_id_seq";
CREATE SEQUENCE "user_svc"."user_browse_history_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for user_favorite_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "user_svc"."user_favorite_id_seq";
CREATE SEQUENCE "user_svc"."user_favorite_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for users_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "user_svc"."users_id_seq";
CREATE SEQUENCE "user_svc"."users_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for address
-- ----------------------------
DROP TABLE IF EXISTS "user_svc"."address";
CREATE TABLE "user_svc"."address" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "user_id" int8 NOT NULL,
  "receiver_name" varchar(100) COLLATE "pg_catalog"."default",
  "phone" varchar(20) COLLATE "pg_catalog"."default",
  "province" varchar(50) COLLATE "pg_catalog"."default",
  "city" varchar(50) COLLATE "pg_catalog"."default",
  "district" varchar(50) COLLATE "pg_catalog"."default",
  "detail" varchar(500) COLLATE "pg_catalog"."default",
  "is_default" int4 DEFAULT 0,
  "create_time" timestamp(6),
  "update_time" timestamp(6)
)
;
COMMENT ON COLUMN "user_svc"."address"."is_default" IS '1=默认地址, 0=非默认';
COMMENT ON TABLE "user_svc"."address" IS '收货地址簿';

-- ----------------------------
-- Table structure for flyway_schema_history
-- ----------------------------
DROP TABLE IF EXISTS "user_svc"."flyway_schema_history";
CREATE TABLE "user_svc"."flyway_schema_history" (
  "installed_rank" int4 NOT NULL,
  "version" varchar(50) COLLATE "pg_catalog"."default",
  "description" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "type" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "script" varchar(1000) COLLATE "pg_catalog"."default" NOT NULL,
  "checksum" int4,
  "installed_by" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "installed_on" timestamp(6) NOT NULL DEFAULT now(),
  "execution_time" int4 NOT NULL,
  "success" bool NOT NULL
)
;

-- ----------------------------
-- Table structure for user_browse_history
-- ----------------------------
DROP TABLE IF EXISTS "user_svc"."user_browse_history";
CREATE TABLE "user_svc"."user_browse_history" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "user_id" int8 NOT NULL,
  "product_id" int8 NOT NULL,
  "source" varchar(100) COLLATE "pg_catalog"."default",
  "duration_sec" int4,
  "create_time" timestamp(6)
)
;
COMMENT ON TABLE "user_svc"."user_browse_history" IS '商品浏览历史(去重后保留最新一条)';

-- ----------------------------
-- Table structure for user_favorite
-- ----------------------------
DROP TABLE IF EXISTS "user_svc"."user_favorite";
CREATE TABLE "user_svc"."user_favorite" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "user_id" int8 NOT NULL,
  "product_id" int8 NOT NULL,
  "create_time" timestamp(6)
)
;
COMMENT ON TABLE "user_svc"."user_favorite" IS '用户收藏';

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "user_svc"."users";
CREATE TABLE "user_svc"."users" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "username" varchar(255) COLLATE "pg_catalog"."default",
  "phone" varchar(20) COLLATE "pg_catalog"."default",
  "password" varchar(255) COLLATE "pg_catalog"."default",
  "avatar_url" varchar(500) COLLATE "pg_catalog"."default",
  "gender" int4,
  "age_range" varchar(20) COLLATE "pg_catalog"."default",
  "skin_type" varchar(50) COLLATE "pg_catalog"."default",
  "preference_tags" jsonb,
  "status" int4 DEFAULT 1,
  "create_time" timestamp(6),
  "update_time" timestamp(6),
  "is_test" bool NOT NULL DEFAULT false,
  "last_login_at" timestamp(6)
)
;
COMMENT ON COLUMN "user_svc"."users"."gender" IS '0=未知, 1=男, 2=女';
COMMENT ON COLUMN "user_svc"."users"."status" IS '1=正常, 0=禁用';
COMMENT ON COLUMN "user_svc"."users"."is_test" IS '是否测试账号(由 POST /auth/test-login 创建)';
COMMENT ON COLUMN "user_svc"."users"."last_login_at" IS '最后登录时间,清理任务按 N 天未登录判定';
COMMENT ON TABLE "user_svc"."users" IS '用户主表';

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "user_svc"."address_id_seq"
OWNED BY "user_svc"."address"."id";
SELECT setval('"user_svc"."address_id_seq"', 3, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "user_svc"."user_browse_history_id_seq"
OWNED BY "user_svc"."user_browse_history"."id";
SELECT setval('"user_svc"."user_browse_history_id_seq"', 21, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "user_svc"."user_favorite_id_seq"
OWNED BY "user_svc"."user_favorite"."id";
SELECT setval('"user_svc"."user_favorite_id_seq"', 2, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "user_svc"."users_id_seq"
OWNED BY "user_svc"."users"."id";
SELECT setval('"user_svc"."users_id_seq"', 18, true);

-- ----------------------------
-- Indexes structure for table address
-- ----------------------------
CREATE INDEX "idx_address_user_id" ON "user_svc"."address" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table address
-- ----------------------------
ALTER TABLE "user_svc"."address" ADD CONSTRAINT "address_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table flyway_schema_history
-- ----------------------------
CREATE INDEX "flyway_schema_history_s_idx" ON "user_svc"."flyway_schema_history" USING btree (
  "success" "pg_catalog"."bool_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table flyway_schema_history
-- ----------------------------
ALTER TABLE "user_svc"."flyway_schema_history" ADD CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank");

-- ----------------------------
-- Indexes structure for table user_browse_history
-- ----------------------------
CREATE INDEX "idx_ubh_user_id" ON "user_svc"."user_browse_history" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "idx_ubh_user_product" ON "user_svc"."user_browse_history" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  "product_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table user_browse_history
-- ----------------------------
ALTER TABLE "user_svc"."user_browse_history" ADD CONSTRAINT "user_browse_history_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table user_favorite
-- ----------------------------
CREATE INDEX "idx_uf_user_id" ON "user_svc"."user_favorite" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "idx_uf_user_product" ON "user_svc"."user_favorite" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  "product_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table user_favorite
-- ----------------------------
ALTER TABLE "user_svc"."user_favorite" ADD CONSTRAINT "user_favorite_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table users
-- ----------------------------
CREATE INDEX "idx_users_is_test_last_login" ON "user_svc"."users" USING btree (
  "is_test" "pg_catalog"."bool_ops" ASC NULLS LAST,
  "last_login_at" "pg_catalog"."timestamp_ops" ASC NULLS LAST
) WHERE is_test = true;
CREATE INDEX "idx_users_phone" ON "user_svc"."users" USING btree (
  "phone" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table users
-- ----------------------------
ALTER TABLE "user_svc"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");
