-- =====================================================================
-- 002_admin_svc.sql — admin_svc schema 完整结构快照(开发期参考)
-- 来源:Navicat Premium 导出 PostgreSQL 16(2026-07-21)
-- 警告:不要直接跑! 含 DROP TABLE IF EXISTS,会清空现有数据。
-- 用途:了解数据库结构 / 对照 Flyway V1 迁移 / 新人入门。
-- =====================================================================


-- ----------------------------
-- Sequence structure for admin_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "admin_svc"."admin_id_seq";
CREATE SEQUENCE "admin_svc"."admin_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for admin
-- ----------------------------
DROP TABLE IF EXISTS "admin_svc"."admin";
CREATE TABLE "admin_svc"."admin" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "username" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "role" varchar(32) COLLATE "pg_catalog"."default" DEFAULT 'ADMIN'::character varying,
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "admin_svc"."admin"."role" IS 'ADMIN / SUPER_ADMIN(预留)';
COMMENT ON TABLE "admin_svc"."admin" IS '管理员账号(admin-bff 专属)';

-- ----------------------------
-- Table structure for flyway_schema_history
-- ----------------------------
DROP TABLE IF EXISTS "admin_svc"."flyway_schema_history";
CREATE TABLE "admin_svc"."flyway_schema_history" (
  "installed_rank" int4 NOT NULL,
  "version" varchar(50) COLLATE "pg_catalog"."default",
  "description" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "type" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "script" varchar(1000) COLLATE "pg_catalog"."default" NOT NULL,
  "checksum" int4,
  "installed_by" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "installed_on" timestamp(6) NOT NULL DEFAULT now(),
  "execution_time" int4 NOT NULL,
  "success" bool NOT NULL
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "admin_svc"."admin_id_seq"
OWNED BY "admin_svc"."admin"."id";
SELECT setval('"admin_svc"."admin_id_seq"', 1, true);

-- ----------------------------
-- Indexes structure for table admin
-- ----------------------------
CREATE UNIQUE INDEX "uk_admin_username" ON "admin_svc"."admin" USING btree (
  "username" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table admin
-- ----------------------------
ALTER TABLE "admin_svc"."admin" ADD CONSTRAINT "admin_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table flyway_schema_history
-- ----------------------------
CREATE INDEX "flyway_schema_history_s_idx" ON "admin_svc"."flyway_schema_history" USING btree (
  "success" "pg_catalog"."bool_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table flyway_schema_history
-- ----------------------------
ALTER TABLE "admin_svc"."flyway_schema_history" ADD CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank");
