-- =====================================================================
-- 003_chat_svc.sql — chat_svc schema 完整结构快照(开发期参考)
-- 来源:Navicat Premium 导出 PostgreSQL 16(2026-07-21)
-- 警告:不要直接跑! 含 DROP TABLE IF EXISTS,会清空现有数据。
-- 用途:了解数据库结构 / 对照 Flyway V1/V2/V3/V4 迁移 / 新人入门。
-- =====================================================================


-- ----------------------------
-- Sequence structure for conversation_context_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "chat_svc"."conversation_context_id_seq";
CREATE SEQUENCE "chat_svc"."conversation_context_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for conversation_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "chat_svc"."conversation_id_seq";
CREATE SEQUENCE "chat_svc"."conversation_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for knowledge_chunk_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "chat_svc"."knowledge_chunk_id_seq";
CREATE SEQUENCE "chat_svc"."knowledge_chunk_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for knowledge_doc_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "chat_svc"."knowledge_doc_id_seq";
CREATE SEQUENCE "chat_svc"."knowledge_doc_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for message_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "chat_svc"."message_id_seq";
CREATE SEQUENCE "chat_svc"."message_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for notice_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "chat_svc"."notice_id_seq";
CREATE SEQUENCE "chat_svc"."notice_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for qa_log_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "chat_svc"."qa_log_id_seq";
CREATE SEQUENCE "chat_svc"."qa_log_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for qa_unanswered_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "chat_svc"."qa_unanswered_id_seq";
CREATE SEQUENCE "chat_svc"."qa_unanswered_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for agent_run
-- ----------------------------
DROP TABLE IF EXISTS "chat_svc"."agent_run";
CREATE TABLE "chat_svc"."agent_run" (
  "id" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "run_id" varchar(64) COLLATE "pg_catalog"."default",
  "trace_id" varchar(64) COLLATE "pg_catalog"."default",
  "conversation_id" varchar(64) COLLATE "pg_catalog"."default",
  "user_id" varchar(64) COLLATE "pg_catalog"."default",
  "status" varchar(32) COLLATE "pg_catalog"."default",
  "goal" varchar(512) COLLATE "pg_catalog"."default",
  "intent" varchar(255) COLLATE "pg_catalog"."default",
  "start_time" timestamp(6),
  "end_time" timestamp(6),
  "input" text COLLATE "pg_catalog"."default",
  "output" text COLLATE "pg_catalog"."default",
  "error_message" text COLLATE "pg_catalog"."default",
  "error_code" varchar(64) COLLATE "pg_catalog"."default",
  "created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Table structure for agent_step
-- ----------------------------
DROP TABLE IF EXISTS "chat_svc"."agent_step";
CREATE TABLE "chat_svc"."agent_step" (
  "id" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "run_id" varchar(64) COLLATE "pg_catalog"."default",
  "step_type" varchar(64) COLLATE "pg_catalog"."default",
  "step_name" varchar(255) COLLATE "pg_catalog"."default",
  "status" varchar(32) COLLATE "pg_catalog"."default",
  "input" text COLLATE "pg_catalog"."default",
  "output" text COLLATE "pg_catalog"."default",
  "error_message" text COLLATE "pg_catalog"."default",
  "start_time" timestamp(6),
  "end_time" timestamp(6),
  "created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "duration_ms" int8,
  "tool_call_id" varchar(64) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for conversation
-- ----------------------------
DROP TABLE IF EXISTS "chat_svc"."conversation";
CREATE TABLE "chat_svc"."conversation" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "user_id" int8 NOT NULL,
  "title" varchar(255) COLLATE "pg_catalog"."default",
  "scene" varchar(64) COLLATE "pg_catalog"."default",
  "is_pinned" int2 DEFAULT 0,
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Table structure for conversation_context
-- ----------------------------
DROP TABLE IF EXISTS "chat_svc"."conversation_context";
CREATE TABLE "chat_svc"."conversation_context" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "conversation_id" int8,
  "user_id" int8,
  "summary" text COLLATE "pg_catalog"."default",
  "embedding" text COLLATE "pg_catalog"."default",
  "user_preferences" text COLLATE "pg_catalog"."default",
  "mentioned_products" text COLLATE "pg_catalog"."default",
  "window_size" int4 DEFAULT 10,
  "importance_score" float8,
  "update_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Table structure for flyway_schema_history
-- ----------------------------
DROP TABLE IF EXISTS "chat_svc"."flyway_schema_history";
CREATE TABLE "chat_svc"."flyway_schema_history" (
  "installed_rank" int4 NOT NULL,
  "version" varchar(50) COLLATE "pg_catalog"."default",
  "description" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "type" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "script" varchar(1000) COLLATE "pg_catalog"."default" NOT NULL,
  "checksum" int4,
  "installed_by" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "installed_on" timestamp(6) NOT NULL DEFAULT now(),
  "execution_time" int4 NOT NULL,
  "success" bool NOT NULL
)
;

-- ----------------------------
-- Table structure for knowledge_chunk
-- ----------------------------
DROP TABLE IF EXISTS "chat_svc"."knowledge_chunk";
CREATE TABLE "chat_svc"."knowledge_chunk" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "doc_id" int8,
  "product_id" int8,
  "chunk_text" text COLLATE "pg_catalog"."default",
  "chunk_index" int4,
  "chunk_type" varchar(32) COLLATE "pg_catalog"."default",
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Table structure for knowledge_doc
-- ----------------------------
DROP TABLE IF EXISTS "chat_svc"."knowledge_doc";
CREATE TABLE "chat_svc"."knowledge_doc" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "doc_name" varchar(255) COLLATE "pg_catalog"."default",
  "file_path" varchar(512) COLLATE "pg_catalog"."default",
  "category_id" int8,
  "doc_type" varchar(64) COLLATE "pg_catalog"."default",
  "status" varchar(32) COLLATE "pg_catalog"."default",
  "error_message" text COLLATE "pg_catalog"."default",
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "object_key" varchar(512) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for message
-- ----------------------------
DROP TABLE IF EXISTS "chat_svc"."message";
CREATE TABLE "chat_svc"."message" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "conversation_id" int8,
  "role" varchar(32) COLLATE "pg_catalog"."default",
  "content" text COLLATE "pg_catalog"."default",
  "message_type" varchar(32) COLLATE "pg_catalog"."default",
  "product_cards" jsonb,
  "confirm_card" jsonb,
  "cart_selection" jsonb,
  "image_url" varchar(512) COLLATE "pg_catalog"."default",
  "sources" text COLLATE "pg_catalog"."default",
  "task_type" varchar(64) COLLATE "pg_catalog"."default",
  "importance_score" float8,
  "feedback_type" varchar(32) COLLATE "pg_catalog"."default",
  "feedback_time" timestamp(6),
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "status" varchar(16) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'done'::character varying,
  "stopped_reason" varchar(32) COLLATE "pg_catalog"."default",
  "stopped_at" timestamp(6),
  "agent_meta" jsonb
)
;

-- ----------------------------
-- Table structure for notice
-- ----------------------------
DROP TABLE IF EXISTS "chat_svc"."notice";
CREATE TABLE "chat_svc"."notice" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "title" varchar(255) COLLATE "pg_catalog"."default",
  "content" text COLLATE "pg_catalog"."default",
  "notice_type" varchar(64) COLLATE "pg_catalog"."default",
  "file_path" varchar(512) COLLATE "pg_catalog"."default",
  "is_active" int2 DEFAULT 1,
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Table structure for qa_log
-- ----------------------------
DROP TABLE IF EXISTS "chat_svc"."qa_log";
CREATE TABLE "chat_svc"."qa_log" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "user_id" int8,
  "conversation_id" int8,
  "question" text COLLATE "pg_catalog"."default",
  "answer" text COLLATE "pg_catalog"."default",
  "task_type" varchar(64) COLLATE "pg_catalog"."default",
  "duration_ms" int8,
  "feedback_type" varchar(32) COLLATE "pg_catalog"."default",
  "feedback_time" timestamp(6),
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Table structure for qa_unanswered
-- ----------------------------
DROP TABLE IF EXISTS "chat_svc"."qa_unanswered";
CREATE TABLE "chat_svc"."qa_unanswered" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "question" text COLLATE "pg_catalog"."default",
  "count" int4,
  "last_user_id" int8,
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Table structure for tool_call
-- ----------------------------
DROP TABLE IF EXISTS "chat_svc"."tool_call";
CREATE TABLE "chat_svc"."tool_call" (
  "id" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "tool_call_id" varchar(64) COLLATE "pg_catalog"."default",
  "run_id" varchar(64) COLLATE "pg_catalog"."default",
  "tool_name" varchar(128) COLLATE "pg_catalog"."default",
  "input_params" text COLLATE "pg_catalog"."default",
  "output" text COLLATE "pg_catalog"."default",
  "status" varchar(32) COLLATE "pg_catalog"."default",
  "duration_ms" int8,
  "error_message" text COLLATE "pg_catalog"."default",
  "timestamp" timestamp(6),
  "created_at" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "chat_svc"."conversation_context_id_seq"
OWNED BY "chat_svc"."conversation_context"."id";
SELECT setval('"chat_svc"."conversation_context_id_seq"', 12, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "chat_svc"."conversation_id_seq"
OWNED BY "chat_svc"."conversation"."id";
SELECT setval('"chat_svc"."conversation_id_seq"', 69, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "chat_svc"."knowledge_chunk_id_seq"
OWNED BY "chat_svc"."knowledge_chunk"."id";
SELECT setval('"chat_svc"."knowledge_chunk_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "chat_svc"."knowledge_doc_id_seq"
OWNED BY "chat_svc"."knowledge_doc"."id";
SELECT setval('"chat_svc"."knowledge_doc_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "chat_svc"."message_id_seq"
OWNED BY "chat_svc"."message"."id";
SELECT setval('"chat_svc"."message_id_seq"', 233, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "chat_svc"."notice_id_seq"
OWNED BY "chat_svc"."notice"."id";
SELECT setval('"chat_svc"."notice_id_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "chat_svc"."qa_log_id_seq"
OWNED BY "chat_svc"."qa_log"."id";
SELECT setval('"chat_svc"."qa_log_id_seq"', 86, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "chat_svc"."qa_unanswered_id_seq"
OWNED BY "chat_svc"."qa_unanswered"."id";
SELECT setval('"chat_svc"."qa_unanswered_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table agent_run
-- ----------------------------
CREATE INDEX "idx_arun_run" ON "chat_svc"."agent_run" USING btree (
  "run_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table agent_run
-- ----------------------------
ALTER TABLE "chat_svc"."agent_run" ADD CONSTRAINT "agent_run_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table agent_step
-- ----------------------------
CREATE INDEX "idx_astep_run" ON "chat_svc"."agent_step" USING btree (
  "run_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table agent_step
-- ----------------------------
ALTER TABLE "chat_svc"."agent_step" ADD CONSTRAINT "agent_step_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table conversation
-- ----------------------------
CREATE INDEX "idx_conv_user" ON "chat_svc"."conversation" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table conversation
-- ----------------------------
ALTER TABLE "chat_svc"."conversation" ADD CONSTRAINT "conversation_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table conversation_context
-- ----------------------------
CREATE INDEX "idx_cctx_conv" ON "chat_svc"."conversation_context" USING btree (
  "conversation_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table conversation_context
-- ----------------------------
ALTER TABLE "chat_svc"."conversation_context" ADD CONSTRAINT "conversation_context_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table flyway_schema_history
-- ----------------------------
CREATE INDEX "flyway_schema_history_s_idx" ON "chat_svc"."flyway_schema_history" USING btree (
  "success" "pg_catalog"."bool_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table flyway_schema_history
-- ----------------------------
ALTER TABLE "chat_svc"."flyway_schema_history" ADD CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank");

-- ----------------------------
-- Indexes structure for table knowledge_chunk
-- ----------------------------
CREATE INDEX "idx_kchunk_doc" ON "chat_svc"."knowledge_chunk" USING btree (
  "doc_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table knowledge_chunk
-- ----------------------------
ALTER TABLE "chat_svc"."knowledge_chunk" ADD CONSTRAINT "knowledge_chunk_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table knowledge_doc
-- ----------------------------
ALTER TABLE "chat_svc"."knowledge_doc" ADD CONSTRAINT "knowledge_doc_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table message
-- ----------------------------
CREATE INDEX "idx_msg_conv" ON "chat_svc"."message" USING btree (
  "conversation_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "idx_msg_status" ON "chat_svc"."message" USING btree (
  "status" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table message
-- ----------------------------
ALTER TABLE "chat_svc"."message" ADD CONSTRAINT "message_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table notice
-- ----------------------------
ALTER TABLE "chat_svc"."notice" ADD CONSTRAINT "notice_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table qa_log
-- ----------------------------
CREATE INDEX "idx_qalog_user" ON "chat_svc"."qa_log" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table qa_log
-- ----------------------------
ALTER TABLE "chat_svc"."qa_log" ADD CONSTRAINT "qa_log_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table qa_unanswered
-- ----------------------------
ALTER TABLE "chat_svc"."qa_unanswered" ADD CONSTRAINT "qa_unanswered_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table tool_call
-- ----------------------------
ALTER TABLE "chat_svc"."tool_call" ADD CONSTRAINT "tool_call_pkey" PRIMARY KEY ("id");
