-- =====================================================================
-- 004_product_svc.sql — product_svc schema 完整结构快照(开发期参考)
-- 来源:Navicat Premium 导出 PostgreSQL 16(2026-07-21)
-- 警告:不要直接跑! 含 DROP TABLE IF EXISTS,会清空现有数据。
-- 用途:了解数据库结构 / 对照 Flyway V1/V2 迁移 / 新人入门。
-- =====================================================================


-- ----------------------------
-- Sequence structure for category_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "product_svc"."category_id_seq";
CREATE SEQUENCE "product_svc"."category_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for product_faq_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "product_svc"."product_faq_id_seq";
CREATE SEQUENCE "product_svc"."product_faq_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for product_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "product_svc"."product_id_seq";
CREATE SEQUENCE "product_svc"."product_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for product_image_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "product_svc"."product_image_id_seq";
CREATE SEQUENCE "product_svc"."product_image_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for product_review_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "product_svc"."product_review_id_seq";
CREATE SEQUENCE "product_svc"."product_review_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for product_sku_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "product_svc"."product_sku_id_seq";
CREATE SEQUENCE "product_svc"."product_sku_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for recommendation_log_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "product_svc"."recommendation_log_id_seq";
CREATE SEQUENCE "product_svc"."recommendation_log_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for category
-- ----------------------------
DROP TABLE IF EXISTS "product_svc"."category";
CREATE TABLE "product_svc"."category" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "description" varchar(500) COLLATE "pg_catalog"."default",
  "icon_url" varchar(500) COLLATE "pg_catalog"."default",
  "sort_order" int4 DEFAULT 0,
  "is_active" int2 DEFAULT 1,
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON TABLE "product_svc"."category" IS '商品分类(扁平一级,无 parent_id)';

-- ----------------------------
-- Table structure for flyway_schema_history
-- ----------------------------
DROP TABLE IF EXISTS "product_svc"."flyway_schema_history";
CREATE TABLE "product_svc"."flyway_schema_history" (
  "installed_rank" int4 NOT NULL,
  "version" varchar(50) COLLATE "pg_catalog"."default",
  "description" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "type" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "script" varchar(1000) COLLATE "pg_catalog"."default" NOT NULL,
  "checksum" int4,
  "installed_by" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "installed_on" timestamp(6) NOT NULL DEFAULT now(),
  "execution_time" int4 NOT NULL,
  "success" bool NOT NULL
)
;

-- ----------------------------
-- Table structure for product
-- ----------------------------
DROP TABLE IF EXISTS "product_svc"."product";
CREATE TABLE "product_svc"."product" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "product_code" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "category_id" int8 NOT NULL,
  "title" varchar(500) COLLATE "pg_catalog"."default" NOT NULL,
  "brand" varchar(100) COLLATE "pg_catalog"."default",
  "sub_category" varchar(50) COLLATE "pg_catalog"."default",
  "base_price" numeric(10,2) NOT NULL DEFAULT 0.00,
  "image_url" varchar(500) COLLATE "pg_catalog"."default",
  "description" text COLLATE "pg_catalog"."default",
  "tags" varchar(1000) COLLATE "pg_catalog"."default",
  "rating" numeric(3,2) DEFAULT 0.00,
  "review_count" int4 DEFAULT 0,
  "sales_count" int4 DEFAULT 0,
  "status" int2 DEFAULT 1,
  "embedding_status" int2 DEFAULT 0,
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "product_svc"."product"."status" IS '1=上架, 0=下架';
COMMENT ON COLUMN "product_svc"."product"."embedding_status" IS '0=未处理, 1=已生成向量';
COMMENT ON TABLE "product_svc"."product" IS '商品主表';

-- ----------------------------
-- Table structure for product_faq
-- ----------------------------
DROP TABLE IF EXISTS "product_svc"."product_faq";
CREATE TABLE "product_svc"."product_faq" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "product_id" int8 NOT NULL,
  "question" varchar(500) COLLATE "pg_catalog"."default" NOT NULL,
  "answer" text COLLATE "pg_catalog"."default" NOT NULL,
  "sort_order" int4 DEFAULT 0,
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;

-- ----------------------------
-- Table structure for product_image
-- ----------------------------
DROP TABLE IF EXISTS "product_svc"."product_image";
CREATE TABLE "product_svc"."product_image" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "product_id" int8 NOT NULL,
  "image_url" varchar(500) COLLATE "pg_catalog"."default" NOT NULL,
  "image_type" varchar(20) COLLATE "pg_catalog"."default" DEFAULT 'detail'::character varying,
  "sort_order" int4 DEFAULT 0,
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "product_svc"."product_image"."image_type" IS 'main=主图, detail=详情图, scene=场景图';

-- ----------------------------
-- Table structure for product_review
-- ----------------------------
DROP TABLE IF EXISTS "product_svc"."product_review";
CREATE TABLE "product_svc"."product_review" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "product_id" int8 NOT NULL,
  "user_id" int8,
  "nickname" varchar(50) COLLATE "pg_catalog"."default" DEFAULT '匿名用户'::character varying,
  "rating" int2 NOT NULL,
  "content" text COLLATE "pg_catalog"."default" NOT NULL,
  "is_anonymous" int2 DEFAULT 0,
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "product_svc"."product_review"."rating" IS '1-5 星';

-- ----------------------------
-- Table structure for product_sku
-- ----------------------------
DROP TABLE IF EXISTS "product_svc"."product_sku";
CREATE TABLE "product_svc"."product_sku" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "product_id" int8 NOT NULL,
  "sku_code" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "properties" jsonb,
  "price" numeric(10,2) NOT NULL,
  "stock" int4 DEFAULT 999,
  "is_default" int2 DEFAULT 0,
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON COLUMN "product_svc"."product_sku"."properties" IS 'JSON 规格键值,如 {"容量":"30ml","颜色":"红"}';
COMMENT ON TABLE "product_svc"."product_sku" IS '商品规格(SKU)';

-- ----------------------------
-- Table structure for recommendation_log
-- ----------------------------
DROP TABLE IF EXISTS "product_svc"."recommendation_log";
CREATE TABLE "product_svc"."recommendation_log" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "user_id" int8,
  "session_id" varchar(64) COLLATE "pg_catalog"."default",
  "message_id" int8,
  "query" text COLLATE "pg_catalog"."default",
  "intent" varchar(50) COLLATE "pg_catalog"."default",
  "recommended_product_ids" jsonb,
  "recommend_reason" text COLLATE "pg_catalog"."default",
  "agent_reasoning" text COLLATE "pg_catalog"."default",
  "user_clicked" int2 DEFAULT 0,
  "user_feedback" int2,
  "create_time" timestamp(6) DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON TABLE "product_svc"."recommendation_log" IS 'AI 商品推荐日志(供离线分析与推荐算法迭代)';

-- ----------------------------
-- Table structure for sync_watermark
-- ----------------------------
DROP TABLE IF EXISTS "product_svc"."sync_watermark";
CREATE TABLE "product_svc"."sync_watermark" (
  "key" varchar(64) COLLATE "pg_catalog"."default" NOT NULL,
  "last_synced_at" timestamptz(6) NOT NULL,
  "updated_at" timestamptz(6) NOT NULL DEFAULT now()
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "product_svc"."category_id_seq"
OWNED BY "product_svc"."category"."id";
SELECT setval('"product_svc"."category_id_seq"', 4, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "product_svc"."product_faq_id_seq"
OWNED BY "product_svc"."product_faq"."id";
SELECT setval('"product_svc"."product_faq_id_seq"', 439, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "product_svc"."product_id_seq"
OWNED BY "product_svc"."product"."id";
SELECT setval('"product_svc"."product_id_seq"', 100, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "product_svc"."product_image_id_seq"
OWNED BY "product_svc"."product_image"."id";
SELECT setval('"product_svc"."product_image_id_seq"', 100, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "product_svc"."product_review_id_seq"
OWNED BY "product_svc"."product_review"."id";
SELECT setval('"product_svc"."product_review_id_seq"', 454, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "product_svc"."product_sku_id_seq"
OWNED BY "product_svc"."product_sku"."id";
SELECT setval('"product_svc"."product_sku_id_seq"', 585, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "product_svc"."recommendation_log_id_seq"
OWNED BY "product_svc"."recommendation_log"."id";
SELECT setval('"product_svc"."recommendation_log_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table category
-- ----------------------------
CREATE INDEX "idx_category_sort" ON "product_svc"."category" USING btree (
  "sort_order" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table category
-- ----------------------------
ALTER TABLE "product_svc"."category" ADD CONSTRAINT "category_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table flyway_schema_history
-- ----------------------------
CREATE INDEX "flyway_schema_history_s_idx" ON "product_svc"."flyway_schema_history" USING btree (
  "success" "pg_catalog"."bool_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table flyway_schema_history
-- ----------------------------
ALTER TABLE "product_svc"."flyway_schema_history" ADD CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank");

-- ----------------------------
-- Indexes structure for table product
-- ----------------------------
CREATE INDEX "idx_product_brand" ON "product_svc"."product" USING btree (
  "brand" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_product_category" ON "product_svc"."product" USING btree (
  "category_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "idx_product_embedding_status" ON "product_svc"."product" USING btree (
  "embedding_status" "pg_catalog"."int2_ops" ASC NULLS LAST
);
CREATE INDEX "idx_product_price" ON "product_svc"."product" USING btree (
  "base_price" "pg_catalog"."numeric_ops" ASC NULLS LAST
);
CREATE INDEX "idx_product_rating" ON "product_svc"."product" USING btree (
  "rating" "pg_catalog"."numeric_ops" DESC NULLS FIRST
);
CREATE INDEX "idx_product_sales" ON "product_svc"."product" USING btree (
  "sales_count" "pg_catalog"."int4_ops" DESC NULLS FIRST
);
CREATE INDEX "idx_product_status" ON "product_svc"."product" USING btree (
  "status" "pg_catalog"."int2_ops" ASC NULLS LAST
);
CREATE INDEX "idx_product_sub_category" ON "product_svc"."product" USING btree (
  "sub_category" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "uk_product_code" ON "product_svc"."product" USING btree (
  "product_code" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table product
-- ----------------------------
ALTER TABLE "product_svc"."product" ADD CONSTRAINT "product_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table product_faq
-- ----------------------------
CREATE INDEX "idx_faq_product" ON "product_svc"."product_faq" USING btree (
  "product_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table product_faq
-- ----------------------------
ALTER TABLE "product_svc"."product_faq" ADD CONSTRAINT "product_faq_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table product_image
-- ----------------------------
CREATE INDEX "idx_image_product" ON "product_svc"."product_image" USING btree (
  "product_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table product_image
-- ----------------------------
ALTER TABLE "product_svc"."product_image" ADD CONSTRAINT "product_image_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table product_review
-- ----------------------------
CREATE INDEX "idx_review_product" ON "product_svc"."product_review" USING btree (
  "product_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "idx_review_rating" ON "product_svc"."product_review" USING btree (
  "rating" "pg_catalog"."int2_ops" ASC NULLS LAST
);
CREATE INDEX "idx_review_user" ON "product_svc"."product_review" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table product_review
-- ----------------------------
ALTER TABLE "product_svc"."product_review" ADD CONSTRAINT "product_review_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table product_sku
-- ----------------------------
CREATE INDEX "idx_sku_product" ON "product_svc"."product_sku" USING btree (
  "product_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "uk_sku_code" ON "product_svc"."product_sku" USING btree (
  "sku_code" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table product_sku
-- ----------------------------
ALTER TABLE "product_svc"."product_sku" ADD CONSTRAINT "product_sku_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table recommendation_log
-- ----------------------------
CREATE INDEX "idx_rec_create_time" ON "product_svc"."recommendation_log" USING btree (
  "create_time" "pg_catalog"."timestamp_ops" DESC NULLS FIRST
);
CREATE INDEX "idx_rec_intent" ON "product_svc"."recommendation_log" USING btree (
  "intent" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_rec_session" ON "product_svc"."recommendation_log" USING btree (
  "session_id" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_rec_user" ON "product_svc"."recommendation_log" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table recommendation_log
-- ----------------------------
ALTER TABLE "product_svc"."recommendation_log" ADD CONSTRAINT "recommendation_log_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table sync_watermark
-- ----------------------------
ALTER TABLE "product_svc"."sync_watermark" ADD CONSTRAINT "sync_watermark_pkey" PRIMARY KEY ("key");
