-- =====================================================================
-- 005_trade_svc.sql — trade_svc schema 完整结构快照(开发期参考)
-- 来源:Navicat Premium 导出 PostgreSQL 16(2026-07-21)
-- 警告:不要直接跑! 含 DROP TABLE IF EXISTS,会清空现有数据。
-- 用途:了解数据库结构 / 对照 Flyway V1 迁移 / 新人入门。
-- =====================================================================


-- ----------------------------
-- Sequence structure for order_item_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "trade_svc"."order_item_id_seq";
CREATE SEQUENCE "trade_svc"."order_item_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for orders_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "trade_svc"."orders_id_seq";
CREATE SEQUENCE "trade_svc"."orders_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for user_cart_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "trade_svc"."user_cart_id_seq";
CREATE SEQUENCE "trade_svc"."user_cart_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for flyway_schema_history
-- ----------------------------
DROP TABLE IF EXISTS "trade_svc"."flyway_schema_history";
CREATE TABLE "trade_svc"."flyway_schema_history" (
  "installed_rank" int4 NOT NULL,
  "version" varchar(50) COLLATE "pg_catalog"."default",
  "description" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "type" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "script" varchar(1000) COLLATE "pg_catalog"."default" NOT NULL,
  "checksum" int4,
  "installed_by" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "installed_on" timestamp(6) NOT NULL DEFAULT now(),
  "execution_time" int4 NOT NULL,
  "success" bool NOT NULL
)
;

-- ----------------------------
-- Table structure for order_item
-- ----------------------------
DROP TABLE IF EXISTS "trade_svc"."order_item";
CREATE TABLE "trade_svc"."order_item" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "order_id" int8 NOT NULL,
  "product_id" int8 NOT NULL,
  "product_title" varchar(200) COLLATE "pg_catalog"."default",
  "product_image" varchar(500) COLLATE "pg_catalog"."default",
  "sku_id" int8,
  "sku_properties" varchar(500) COLLATE "pg_catalog"."default",
  "price" numeric(12,2) NOT NULL,
  "quantity" int4 NOT NULL,
  "total_amount" numeric(12,2) NOT NULL
)
;
COMMENT ON TABLE "trade_svc"."order_item" IS '订单明细(下单时冻结商品/SKU 快照字段)';

-- ----------------------------
-- Table structure for orders
-- ----------------------------
DROP TABLE IF EXISTS "trade_svc"."orders";
CREATE TABLE "trade_svc"."orders" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "user_id" int8 NOT NULL,
  "order_no" varchar(32) COLLATE "pg_catalog"."default" NOT NULL,
  "status" int2 NOT NULL DEFAULT 0,
  "total_amount" numeric(12,2) NOT NULL DEFAULT 0,
  "pay_amount" numeric(12,2) NOT NULL DEFAULT 0,
  "freight_amount" numeric(12,2) NOT NULL DEFAULT 0,
  "address_id" int8,
  "receiver_name" varchar(64) COLLATE "pg_catalog"."default",
  "receiver_phone" varchar(20) COLLATE "pg_catalog"."default",
  "receiver_address" varchar(255) COLLATE "pg_catalog"."default",
  "remark" varchar(500) COLLATE "pg_catalog"."default",
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "pay_time" timestamp(6),
  "delivery_time" timestamp(6),
  "receive_time" timestamp(6),
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "pay_channel" varchar(20) COLLATE "pg_catalog"."default" NOT NULL DEFAULT 'MOCK'::character varying,
  "trade_no" varchar(64) COLLATE "pg_catalog"."default"
)
;
COMMENT ON COLUMN "trade_svc"."orders"."status" IS '0=待付款, 1=待发货, 2=待收货, 3=已完成, 4=已取消';
COMMENT ON COLUMN "trade_svc"."orders"."pay_channel" IS '支付渠道: MOCK(模拟) / ALIPAY_SANDBOX(支付宝沙箱) / 未来加 WECHAT/ALIPAY_PROD 等';
COMMENT ON COLUMN "trade_svc"."orders"."trade_no" IS '支付宝交易号(异步通知里回传,TRADE_SUCCESS 后写入)';
COMMENT ON TABLE "trade_svc"."orders" IS '订单主表(表名 orders 避开 SQL 保留字 order)';

-- ----------------------------
-- Table structure for user_cart
-- ----------------------------
DROP TABLE IF EXISTS "trade_svc"."user_cart";
CREATE TABLE "trade_svc"."user_cart" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "user_id" int8 NOT NULL,
  "product_id" int8 NOT NULL,
  "sku_id" int8,
  "quantity" int4 NOT NULL DEFAULT 1,
  "create_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_time" timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;
COMMENT ON TABLE "trade_svc"."user_cart" IS '购物车(用户维度,一行=一条 cart item)';

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "trade_svc"."order_item_id_seq"
OWNED BY "trade_svc"."order_item"."id";
SELECT setval('"trade_svc"."order_item_id_seq"', 43, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "trade_svc"."orders_id_seq"
OWNED BY "trade_svc"."orders"."id";
SELECT setval('"trade_svc"."orders_id_seq"', 36, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "trade_svc"."user_cart_id_seq"
OWNED BY "trade_svc"."user_cart"."id";
SELECT setval('"trade_svc"."user_cart_id_seq"', 20, true);

-- ----------------------------
-- Indexes structure for table flyway_schema_history
-- ----------------------------
CREATE INDEX "flyway_schema_history_s_idx" ON "trade_svc"."flyway_schema_history" USING btree (
  "success" "pg_catalog"."bool_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table flyway_schema_history
-- ----------------------------
ALTER TABLE "trade_svc"."flyway_schema_history" ADD CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank");

-- ----------------------------
-- Indexes structure for table order_item
-- ----------------------------
CREATE INDEX "idx_order_item_order_id" ON "trade_svc"."order_item" USING btree (
  "order_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table order_item
-- ----------------------------
ALTER TABLE "trade_svc"."order_item" ADD CONSTRAINT "order_item_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table orders
-- ----------------------------
CREATE INDEX "idx_orders_create_time" ON "trade_svc"."orders" USING btree (
  "create_time" "pg_catalog"."timestamp_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "idx_orders_order_no" ON "trade_svc"."orders" USING btree (
  "order_no" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);
CREATE INDEX "idx_orders_status" ON "trade_svc"."orders" USING btree (
  "status" "pg_catalog"."int2_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "idx_orders_trade_no" ON "trade_svc"."orders" USING btree (
  "trade_no" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
) WHERE trade_no IS NOT NULL;
CREATE INDEX "idx_orders_user_id" ON "trade_svc"."orders" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table orders
-- ----------------------------
ALTER TABLE "trade_svc"."orders" ADD CONSTRAINT "orders_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table user_cart
-- ----------------------------
CREATE INDEX "idx_cart_user_id" ON "trade_svc"."user_cart" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE UNIQUE INDEX "idx_cart_user_product_sku" ON "trade_svc"."user_cart" USING btree (
  "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  "product_id" "pg_catalog"."int8_ops" ASC NULLS LAST,
  COALESCE(sku_id, 0::bigint) "pg_catalog"."int8_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table user_cart
-- ----------------------------
ALTER TABLE "trade_svc"."user_cart" ADD CONSTRAINT "user_cart_pkey" PRIMARY KEY ("id");
