-- =====================================================================
-- trade-service 首个 Flyway 迁移
-- schema: trade_svc
-- 3 张业务表:user_cart / orders / order_item
-- 与 monolith Cart/Order/OrderItem entity 字段对齐
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS trade_svc;

SET search_path TO trade_svc;

-- ---------- user_cart(购物车,每行 = 一条 cart item)----------
CREATE TABLE user_cart (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    product_id  BIGINT       NOT NULL,
    sku_id      BIGINT,                                          -- 可空:允许不选规格的商品
    quantity    INTEGER      NOT NULL DEFAULT 1,
    create_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cart_user_id ON user_cart(user_id);
-- 同一用户+商品+SKU 只允许一条(sku 为空时用 COALESCE 转 0 参与唯一约束)
CREATE UNIQUE INDEX idx_cart_user_product_sku ON user_cart(user_id, product_id, COALESCE(sku_id, 0));

COMMENT ON TABLE user_cart IS '购物车(用户维度,一行=一条 cart item)';

-- ---------- orders(订单主表)----------
-- 注意:表名叫 orders 不叫 order,因为 order 是 SQL 保留字
CREATE TABLE orders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT         NOT NULL,
    order_no         VARCHAR(32)    NOT NULL,                    -- 唯一订单号 yyyyMMddHHmmss + 6 位随机
    status           SMALLINT       NOT NULL DEFAULT 0,          -- 0=待付款 1=待发货 2=待收货 3=已完成 4=已取消
    total_amount     NUMERIC(12, 2) NOT NULL DEFAULT 0,
    pay_amount       NUMERIC(12, 2) NOT NULL DEFAULT 0,
    freight_amount   NUMERIC(12, 2) NOT NULL DEFAULT 0,
    address_id       BIGINT,                                     -- 关联 user_svc.address.id(跨服务字段)
    receiver_name    VARCHAR(64),
    receiver_phone   VARCHAR(20),
    receiver_address VARCHAR(255),                               -- 快照:省市区+详细拼接
    remark           VARCHAR(500),
    create_time      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pay_time         TIMESTAMP,
    delivery_time    TIMESTAMP,
    receive_time     TIMESTAMP,
    update_time      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_orders_order_no ON orders(order_no);
CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_create_time ON orders(create_time);

COMMENT ON TABLE orders IS '订单主表(表名 orders 避开 SQL 保留字 order)';
COMMENT ON COLUMN orders.status IS '0=待付款, 1=待发货, 2=待收货, 3=已完成, 4=已取消';

-- ---------- order_item(订单明细)----------
CREATE TABLE order_item (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT         NOT NULL,
    product_id     BIGINT         NOT NULL,
    product_title  VARCHAR(200),                                 -- 快照
    product_image  VARCHAR(500),                                 -- 快照
    sku_id         BIGINT,
    sku_properties VARCHAR(500),                                 -- 快照,如 "容量: 30ml 经典装"
    price          NUMERIC(12, 2) NOT NULL,                      -- 下单时快照价
    quantity       INTEGER        NOT NULL,
    total_amount   NUMERIC(12, 2) NOT NULL                       -- price * quantity
);

CREATE INDEX idx_order_item_order_id ON order_item(order_id);

COMMENT ON TABLE order_item IS '订单明细(下单时冻结商品/SKU 快照字段)';
