# =====================================================================
# admin-bff 配置(Ph3:接入 Nacos discovery)
# =====================================================================
server:
  port: 8090

spring:
  application:
    name: admin-bff
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
