<template>
  <view class="page detail-page">
    <view v-if="loading" class="loading-wrap"><uni-load-more status="loading" :contentText="loadText" /></view>
    <EmptyState v-else-if="!order" title="订单不存在" description="请返回订单列表重新选择。" />
    <scroll-view v-else scroll-y class="detail-scroll">
      <view class="status-card" :class="`status-bg-${order.status}`"><text class="status-title">{{ statusTitle(order.status) }}</text><text class="status-desc">{{ statusDesc(order.status) }}</text></view>
      <view class="address-card"><uni-icons type="location" size="21" color="#14b8a6" /><view class="address-main"><view class="receiver-row"><text class="receiver">{{ order.receiverName || '' }}</text><text class="phone">{{ order.receiverPhone || '' }}</text></view><text class="address-text">{{ order.receiverAddress || '' }}</text></view></view>
      <view class="section-card"><text class="section-title">商品信息</text><view v-for="item in order.items || []" :key="item.id || item.productId" class="goods-row" @tap="goProduct(item)"><view class="thumb"><image v-if="itemImage(item)" :src="itemImage(item)" mode="aspectFill" /><uni-icons v-else type="image" size="24" color="#98a2b3" /></view><view class="goods-info"><text class="goods-title">{{ item.productTitle || '订单商品' }}</text><text v-if="item.skuProperties" class="sku-text">{{ item.skuProperties }}</text><view class="price-line"><text class="price">{{ formatMoney(item.price || 0) }}</text><text class="qty">x{{ item.quantity || 1 }}</text></view></view></view></view>
      <view class="section-card"><text class="section-title">价格明细</text><view class="info-row"><text>商品金额</text><text>{{ formatMoney(order.totalAmount || 0) }}</text></view><view class="info-row"><text>运费</text><text>{{ Number(order.freightAmount || 0) > 0 ? formatMoney(order.freightAmount) : '免运费' }}</text></view><view class="divider"></view><view class="info-row total"><text>实付</text><text>{{ formatMoney(order.payAmount || order.totalAmount || 0) }}</text></view></view>
      <view class="section-card"><text class="section-title">订单信息</text><view class="info-row"><text>订单号</text><text>{{ order.orderNo || order.id }}</text></view><view class="info-row"><text>创建时间</text><text>{{ dateText(order.createTime) }}</text></view><view v-if="order.payTime" class="info-row"><text>支付时间</text><text>{{ dateText(order.payTime) }}</text></view><view v-if="order.deliveryTime" class="info-row"><text>发货时间</text><text>{{ dateText(order.deliveryTime) }}</text></view><view v-if="order.receiveTime" class="info-row"><text>收货时间</text><text>{{ dateText(order.receiveTime) }}</text></view><view v-if="order.remark" class="info-row"><text>备注</text><text>{{ order.remark }}</text></view></view>
      <view class="bottom-spacer"></view>
    </scroll-view>
    <view v-if="order" class="action-bar"><button v-if="order.status === 0" class="outline-btn" @tap="confirmCancel">取消订单</button><button v-if="order.status === 0" class="primary-btn" @tap="pay">立即支付</button><button v-if="order.status === 1 || order.status === 2" class="primary-btn" @tap="confirmReceive">确认收货</button><button v-if="order.status === 3 || order.status === 4" class="danger-btn" @tap="confirmDelete">删除订单</button></view>
  </view>
</template>
<script>
import EmptyState from '../../components/EmptyState.vue'
import { cancelOrder, deleteOrder, getOrderDetail, payOrder, receiveOrder } from '../../api/order'
import { formatMoney, orderStatusText } from '../../utils/format'
import { buildImageUrl } from '../../utils/image'
import { requireLogin } from '../../utils/routeGuard'
export default { components:{EmptyState}, data(){ return { id:null, order:null, loading:false, loadText:{contentdown:'加载更多',contentrefresh:'正在加载...',contentnomore:'没有更多了'} } }, onLoad(query={}){ if(!requireLogin('/pages/order-detail/order-detail')) return; this.id=Number(query.id); this.loadDetail() }, methods:{ formatMoney(value){return formatMoney(value)}, async loadDetail(){ if(!this.id) return; this.loading=true; try{ this.order=await getOrderDetail(this.id) } catch(e){ uni.showToast({title:'订单加载失败',icon:'none'}) } finally{ this.loading=false } }, statusTitle(status){ return orderStatusText(status) }, statusDesc(status){ const map={0:'请尽快完成支付',1:'商家正在准备发货',2:'商品已发出，请留意签收',3:'交易已完成',4:'订单已取消'}; return map[status] || '订单状态未知' }, dateText(value){ return value ? String(value).replace('T',' ').slice(0,19) : '' }, itemImage(item){ return buildImageUrl(item.productImage || item.imageUrl || '') }, goProduct(item){ if(item.productId) uni.navigateTo({url:`/pages/product-detail/product-detail?id=${item.productId}`}) }, async pay(){ await this.runAction(()=>payOrder(this.id),'支付成功') }, confirmCancel(){ this.confirm('取消订单','确定取消这个订单吗？',()=>this.runAction(()=>cancelOrder(this.id),'订单已取消')) }, confirmReceive(){ this.confirm('确认收货','确认已经收到商品吗？',()=>this.runAction(()=>receiveOrder(this.id),'已确认收货')) }, confirmDelete(){ this.confirm('删除订单','删除后不可恢复，确定删除吗？',async()=>{ await deleteOrder(this.id); uni.showToast({title:'已删除',icon:'none'}); setTimeout(()=>uni.navigateBack(),350) }) }, confirm(title,content,onConfirm){ uni.showModal({title,content,success:(res)=>{ if(res.confirm) onConfirm() }}) }, async runAction(action,message){ try{ this.order=await action(); uni.showToast({title:message,icon:'none'}) } catch(e){ uni.showToast({title:e.message || '操作失败',icon:'none'}) } } } }
</script>
<style scoped>
.detail-page{min-height:100vh;padding:20rpx 22rpx 130rpx}.loading-wrap{padding:120rpx 0}.detail-scroll{height:calc(100vh - 130rpx)}.status-card{padding:30rpx 28rpx;border-radius:22rpx;margin-bottom:18rpx;color:#fff}.status-bg-0{background:#ef4444}.status-bg-1{background:#f97316}.status-bg-2{background:#14b8a6}.status-bg-3{background:#2563eb}.status-bg-4{background:#98a2b3}.status-title{display:block;font-size:38rpx;font-weight:900}.status-desc{display:block;margin-top:8rpx;font-size:25rpx;opacity:.9}.address-card,.section-card{margin-bottom:18rpx;padding:24rpx;border-radius:22rpx;background:#fff;box-shadow:0 10rpx 28rpx rgba(15,118,110,.06)}.address-card{display:flex;gap:14rpx}.address-main{flex:1;min-width:0}.receiver-row{display:flex;gap:14rpx;align-items:center}.receiver{color:#1f2937;font-size:29rpx;font-weight:900}.phone{color:#667085;font-size:25rpx;font-weight:700}.address-text{display:block;margin-top:8rpx;color:#344054;font-size:26rpx;line-height:1.45}.section-title{display:block;margin-bottom:16rpx;color:#1f2937;font-size:29rpx;font-weight:900}.goods-row{display:flex;gap:16rpx;padding:14rpx 0;border-top:1rpx solid #eef2f7}.goods-row:first-of-type{border-top:0}.thumb{display:flex;align-items:center;justify-content:center;width:124rpx;height:124rpx;border-radius:16rpx;background:#f4f8f8;overflow:hidden}.thumb image{width:100%;height:100%}.goods-info{flex:1;min-width:0}.goods-title{display:-webkit-box;overflow:hidden;color:#1f2937;font-size:27rpx;font-weight:800;line-height:1.35;-webkit-line-clamp:2;-webkit-box-orient:vertical}.sku-text{display:block;margin-top:6rpx;color:#667085;font-size:23rpx}.price-line{display:flex;align-items:center;justify-content:space-between;margin-top:12rpx}.price{color:#f97316;font-size:29rpx;font-weight:900}.qty{color:#667085;font-size:24rpx}.info-row{display:flex;justify-content:space-between;gap:20rpx;padding:8rpx 0;color:#344054;font-size:25rpx}.info-row text:last-child{flex:1;text-align:right;word-break:break-all}.info-row.total{font-size:30rpx;font-weight:900;color:#1f2937}.info-row.total text:last-child{color:#f97316}.divider{height:1rpx;background:#eef2f7;margin:10rpx 0}.action-bar{position:fixed;left:0;right:0;bottom:0;display:flex;justify-content:flex-end;gap:16rpx;padding:16rpx 22rpx calc(16rpx + env(safe-area-inset-bottom));background:#fff;box-shadow:0 -8rpx 28rpx rgba(15,118,110,.08)}.outline-btn,.primary-btn,.danger-btn{width:190rpx;height:72rpx;border-radius:999rpx;font-size:27rpx;font-weight:900;line-height:72rpx}.outline-btn{background:#fff;color:#667085;border:1rpx solid #d0d5dd}.primary-btn{background:#14b8a6;color:#fff}.danger-btn{background:#ef4444;color:#fff}.bottom-spacer{height:110rpx}
</style>
