-- =====================================================================
-- admin-bff 首个 Flyway 迁移
-- schema: admin_svc
-- 1 张表:admin(管理员账号)
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS admin_svc;

SET search_path TO admin_svc;

CREATE TABLE admin (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(64)  NOT NULL,
    password    VARCHAR(255) NOT NULL,       -- BCrypt 密文
    role        VARCHAR(32)  DEFAULT 'ADMIN',
    create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_admin_username ON admin(username);

COMMENT ON TABLE admin IS '管理员账号(admin-bff 专属)';
COMMENT ON COLUMN admin.role IS 'ADMIN / SUPER_ADMIN(预留)';
